-- Alliance Org Chart module: R5/R4 responsibility assignments, fully isolated per alliance.
-- Unlike most existing tables (open select, write-restricted), this table restricts
-- SELECT too — an alliance rep must never see another alliance's org chart, only
-- super_admin sees everything. Reuses is_alliance_rep()/is_super_admin() from rls-step3-chunk1.sql.

create table if not exists alliance_org_chart (
  id bigint generated by default as identity primary key,
  alliance text not null,
  role text not null check (role in ('R5','R4')),
  player_name text not null,
  title text not null,
  description text,
  granted_by text,
  created_at timestamptz not null default now()
);

alter table alliance_org_chart enable row level security;
alter table alliance_org_chart force row level security;

create policy "alliance_org_chart_select" on alliance_org_chart for select
  using (is_alliance_rep(current_player(), alliance) or is_super_admin(current_player()));

create policy "alliance_org_chart_insert" on alliance_org_chart for insert
  with check (is_alliance_rep(current_player(), alliance) or is_super_admin(current_player()));

create policy "alliance_org_chart_update" on alliance_org_chart for update
  using (is_alliance_rep(current_player(), alliance) or is_super_admin(current_player()))
  with check (is_alliance_rep(current_player(), alliance) or is_super_admin(current_player()));

create policy "alliance_org_chart_delete" on alliance_org_chart for delete
  using (is_alliance_rep(current_player(), alliance) or is_super_admin(current_player()));

-- Verify after running:
--   select * from pg_policies where tablename = 'alliance_org_chart';
